import { BodyType, CelestialBodyData } from './types';

export const SUN_RADIUS = 16;
export const BASE_ORBIT_SPEED = 0.5;

export const PLANET_DATA: CelestialBodyData[] = [
  {
    id: 'sun',
    name: 'Sol',
    type: BodyType.STAR,
    description: 'A estrela central do nosso sistema solar. É uma esfera quase perfeita de plasma quente.',
    funFact: 'O Sol representa 99,86% da massa total do Sistema Solar.',
    radius: SUN_RADIUS,
    distance: 0,
    speed: 0,
    rotationSpeed: 0.002,
    color: '#FDB813',
    textureUrl: '/textures/texture_sun.jpg',
    axialTilt: 7.25,
  },
  {
    id: 'mercury',
    name: 'Mercúrio',
    type: BodyType.PLANET,
    description: 'O menor e mais interno planeta do Sistema Solar. Tem uma superfície rochosa cheia de crateras.',
    funFact: 'Um ano em Mercúrio dura apenas 88 dias terrestres.',
    radius: 0.6,
    distance: 42,
    speed: 1.6,
    rotationSpeed: 0.004,
    color: '#A5A5A5',
    textureUrl: '/textures/texture_mercury.jpg',
    axialTilt: 0.03,
  },
  {
    id: 'venus',
    name: 'Vênus',
    type: BodyType.PLANET,
    description: 'O segundo planeta a partir do Sol. É o planeta mais quente devido ao efeito estufa extremo.',
    funFact: 'Vênus gira na direção oposta à maioria dos outros planetas.',
    radius: 1.45,
    distance: 55,
    speed: 1.2,
    rotationSpeed: 0.0032,
    color: '#E3BB76',
    textureUrl: '/textures/texture_venus.jpg',
    axialTilt: 177.36,
  },
  {
    id: 'earth',
    name: 'Terra',
    type: BodyType.PLANET,
    description: 'Nosso lar. O único planeta conhecido por abrigar vida, com vastos oceanos de água líquida.',
    funFact: 'A Terra não é uma esfera perfeita, é um esferoide oblato.',
    radius: 1.5,
    distance: 81,
    speed: 1,
    rotationSpeed: 0.008,
    color: '#22A6B3',
    textureUrl: '/textures/texture_earth.jpg',
    axialTilt: 23.44,
    moons: [
      {
        id: 'moon',
        name: 'Lua',
        type: BodyType.MOON,
        description: 'O único satélite natural da Terra, responsável pelas marés.',
        funFact: 'A Lua sempre mostra a mesma face para a Terra.',
        parentId: 'earth',
        radius: 0.27,
        distance: 5,
        speed: 1.6,
        rotationSpeed: 0.01,
        color: '#cfcfcf',
        textureUrl: '/textures/texture_moon.jpg',
      }
    ],
  },
  {
    id: 'mars',
    name: 'Marte',
    type: BodyType.PLANET,
    description: 'Conhecido como o Planeta Vermelho devido ao óxido de ferro em sua superfície.',
    funFact: 'Marte abriga o Monte Olimpo, o vulcão mais alto do Sistema Solar.',
    radius: 0.8,
    distance: 102,
    speed: 0.8,
    rotationSpeed: 0.0072,
    color: '#EB4D4B',
    textureUrl: '/textures/texture_mars.jpg',
    axialTilt: 25.19,
  },
  {
    id: 'jupiter',
    name: 'Júpiter',
    type: BodyType.PLANET,
    description: 'O maior planeta do Sistema Solar. Um gigante gasoso com uma Grande Mancha Vermelha.',
    funFact: 'Júpiter tem mais de 79 luas confirmadas.',
    radius: 6.5,
    distance: 165,
    speed: 0.4,
    rotationSpeed: 0.016,
    color: '#F9CA24',
    textureUrl: '/textures/texture_jupiter.jpg',
    axialTilt: 3.13,
    moons: [
      {
        id: 'io',
        name: 'Io',
        type: BodyType.MOON,
        description: 'Lua vulcânica de Júpiter, a mais ativa do Sistema Solar.',
        funFact: 'Io possui centenas de vulcoes ativos.',
        parentId: 'jupiter',
        radius: 0.25,
        distance: 8.5,
        speed: 2.2,
        rotationSpeed: 0.02,
        color: '#d8a15d',
        textureUrl: '/textures/texture_io.jpg'
      },
      {
        id: 'europa',
        name: 'Europa',
        type: BodyType.MOON,
        description: 'Lua gelada de Júpiter com provável oceano subterrâneo.',
        funFact: 'Europa é um dos principais alvos na busca por vida.',
        parentId: 'jupiter',
        radius: 0.22,
        distance: 10,
        speed: 1.8,
        rotationSpeed: 0.018,
        color: '#cfcfcf',
        textureUrl: '/textures/texture_europa.jpg'
      },
      {
        id: 'ganymede',
        name: 'Ganimedes',
        type: BodyType.MOON,
        description: 'A maior lua do Sistema Solar.',
        funFact: 'Ganimedes é maior que Mercúrio.',
        parentId: 'jupiter',
        radius: 0.35,
        distance: 12,
        speed: 1.4,
        rotationSpeed: 0.015,
        color: '#b8b2a1',
        textureUrl: '/textures/texture_ganimedes.jpg'
      },
      {
        id: 'callisto',
        name: 'Calisto',
        type: BodyType.MOON,
        description: 'Lua antiga e craterada de Júpiter.',
        funFact: 'Calisto tem uma das superfícies mais antigas do Sistema Solar.',
        parentId: 'jupiter',
        radius: 0.32,
        distance: 14,
        speed: 1.1,
        rotationSpeed: 0.012,
        color: '#a88f6f',
        textureUrl: '/textures/texture_calisto.jpg'
      }
    ],
  },
  {
    id: 'saturn',
    name: 'Saturno',
    type: BodyType.PLANET,
    description: 'Famoso por seu sistema de anéis complexo e proeminente, feito principalmente de gelo e rocha.',
    funFact: 'Saturno é o único planeta que é menos denso que a água.',
    radius: 5.5,
    distance: 225,
    speed: 0.3,
    rotationSpeed: 0.0152,
    color: '#F0932B',
    hasRings: true,
    ringColor: '#dcdcdc',
    ringTextureUrl: '/textures/texture_saturn_rings.png',
    textureUrl: '/textures/texture_saturn.jpg',
    axialTilt: 26.73,
    moons: [
      {
        id: 'titan',
        name: 'Titã',
        type: BodyType.MOON,
        description: 'A maior lua de Saturno, com atmosfera densa.',
        funFact: 'Titã possui lagos de metano líquido.',
        parentId: 'saturn',
        radius: 0.34,
        distance: 16,
        speed: 1.2,
        rotationSpeed: 0.012,
        color: '#c9a46b',
        textureUrl: '/textures/texture_titan.jpg'
      },
      {
        id: 'enceladus',
        name: 'Encélado',
        type: BodyType.MOON,
        description: 'Lua gelada de Saturno com gêiseres ativos.',
        funFact: 'Encélado ejeta plumas de água e gelo.',
        parentId: 'saturn',
        radius: 0.08,
        distance: 13,
        speed: 2.4,
        rotationSpeed: 0.02,
        color: '#e6e6e6',
        textureUrl: '/textures/texture_encelado.jpg'
      }
    ],
  },
  {
    id: 'uranus',
    name: 'Urano',
    type: BodyType.PLANET,
    description: 'Um gigante de gelo com uma atmosfera azul-esverdeada composta por água, amônia e metano.',
    funFact: 'Urano gira de lado, com uma inclinação axial de 98 graus.',
    radius: 2.6,
    distance: 285,
    speed: 0.2,
    rotationSpeed: 0.012,
    color: '#7ED6DF',
    textureUrl: '/textures/texture_uranus.jpg',
    axialTilt: 97.77,
  },
  {
    id: 'neptune',
    name: 'Netuno',
    type: BodyType.PLANET,
    description: 'O planeta mais distante do Sol (dos principais). É um gigante de gelo escuro e frio.',
    funFact: 'Netuno tem os ventos mais fortes do Sistema Solar, chegando a 2.100 km/h.',
    radius: 2.5,
    distance: 345,
    speed: 0.1,
    rotationSpeed: 0.0128,
    color: '#4834D4',
    textureUrl: '/textures/texture_neptune.jpg',
    axialTilt: 28.32,
    moons: [
      {
        id: 'triton',
        name: 'Tritão',
        type: BodyType.MOON,
        description: 'Maior lua de Netuno, com órbita retrógrada.',
        funFact: 'Tritão pode ser um objeto capturado do Cinturão de Kuiper.',
        parentId: 'neptune',
        radius: 0.2,
        distance: 6,
        speed: 1.6,
        rotationSpeed: 0.015,
        color: '#cfcfd6',
        textureUrl: '/textures/texture_triton.jpg'
      }
    ],
  }
];
