import { BodyType, CelestialBodyData } from './types';

export const PLANET_DATA: CelestialBodyData[] = [
  {
    id: 'sun',
    name: 'Sol',
    type: BodyType.STAR,
    description: 'O Sol é uma estrela de tamanho médio, localizada no centro do Sistema Solar, e exerce um papel absolutamente fundamental na existência e no funcionamento de tudo ao seu redor. Ele concentra cerca de 99,86% de toda a massa do sistema e é a principal fonte de energia para a Terra, sustentando o clima, os oceanos, a fotossíntese e, consequentemente, a vida. Também é o principal responsável pela organização gravitacional do Sistema Solar, mantendo planetas, luas, asteroides e cometas em órbita.\n\nCom cerca de 4,6 bilhões de anos, o Sol encontra-se atualmente em uma fase estável de sua vida estelar, conhecida como sequência principal. Nessa etapa, ele converte hidrogênio em hélio de forma contínua, liberando enormes quantidades de energia.',
    quickFacts: [
      { label: 'Raio', value: '~696.340 km' },
      { label: 'Diâmetro', value: '~1,39 milhão de km (≈ 109 Terras alinhadas)' },
      { label: 'Massa', value: '~1,989 × 10^30 kg' },
      { label: 'Idade', value: '~4,6 bilhões de anos' },
      { label: 'Temperatura da superfície (fotosfera)', value: '~5.500 °C' },
      { label: 'Temperatura do núcleo', value: '~15 milhões °C' },
      { label: 'Gravidade na superfície', value: '~274 m/s² (≈ 28× a da Terra)' },
      { label: 'Distância média da Terra', value: '~149,6 milhões de km (1 UA)' },
      {
        label: 'Composição',
        value: [
          'Hidrogênio ≈ 73%',
          'Hélio ≈ 25%',
          'Outros elementos ≈ 2% (oxigênio, carbono, ferro, etc.)'
        ]
      }
    ],
    curiosities: [
      '☀️ A luz do Sol leva ~8 minutos e 20 segundos para chegar à Terra',
      '🔥 A coroa solar é mais quente que a superfície, algo que ainda desafia explicações completas',
      '🧲 O campo magnético do Sol se inverte a cada ciclo solar',
      '🌊 O Sol não é sólido — ele gira mais rápido no equador do que nos polos',
      '📦 Caberiam ~1,3 milhão de Terras dentro do Sol',
      '⏳ Ele ainda tem combustível para ~5 bilhões de anos',
      '💥 No futuro, o Sol se tornará uma gigante vermelha, engolindo Mercúrio e Vênus (possivelmente a Terra)'
    ],
    radius: 16,
    distance: 0,
    speed: 0,
    rotationSpeed: 0.002,
    color: '#FDB813',
    textureUrl: '/textures/texture_sun.jpg',
    axialTilt: 7.25,
  },
  {
    id: 'mercury',
    name: 'Mercúrio',
    type: BodyType.PLANET,
    description: 'Mercúrio é o menor planeta do Sistema Solar e o mais próximo do Sol. Sua superfície rochosa é marcada por crateras de impacto, planícies e falhas gigantescas, lembrando muito a Lua. Por ter uma atmosfera extremamente tênue (quase inexistente), ele não consegue reter calor, o que gera variações intensas de temperatura entre o dia e a noite. Apesar de estar colado ao Sol, Mercúrio não é o planeta mais quente: essa posição fica com Vênus, que possui um efeito estufa extremo.\n\nMercúrio também apresenta uma dinâmica curiosa: sua rotação é lenta, mas sua órbita é rápida, o que faz com que um “dia solar” (de um nascer do Sol ao outro) seja mais longo que seu próprio ano.',
    quickFacts: [
      { label: 'Raio', value: '~2.440 km' },
      { label: 'Diâmetro', value: '~4.879 km' },
      { label: 'Massa', value: '~3,30 × 10^23 kg' },
      { label: 'Gravidade na superfície', value: '~3,7 m/s² (≈ 0,38× a da Terra)' },
      { label: 'Distância média do Sol', value: '~57,9 milhões de km (0,39 UA)' },
      { label: 'Período orbital (ano)', value: '~88 dias terrestres' },
      { label: 'Duração do dia solar', value: '~176 dias terrestres' },
      { label: 'Temperatura superficial', value: '~430 °C de dia e ~-180 °C à noite' },
      { label: 'Atmosfera', value: 'Exosfera muito tênue (sódio, potássio, oxigênio, hélio)' }
    ],
    curiosities: [
      '📉 Mercúrio está encolhendo: o planeta esfriou e sua crosta se contraiu',
      '🌡️ Mesmo sendo o mais próximo do Sol, não é o mais quente por quase não ter atmosfera',
      '🧊 Há gelo de água nos polos, protegido em crateras permanentemente sombreadas',
      '🪨 Sua superfície guarda sinais de grandes impactos, incluindo a bacia Caloris',
      '⏱️ Um dia solar em Mercúrio dura cerca de 2 anos mercurianos',
      '🧲 Ele possui um campo magnético global, embora seja fraco em comparação ao da Terra'
    ],
    radius: 0.6,
    distance: 42,
    speed: 1.6,
    rotationSpeed: 0.000137,
    color: '#A5A5A5',
    textureUrl: '/textures/texture_mercury.jpg',
    axialTilt: 0.03,
    orbitalInclination: 7.00,
  },
  {
    id: 'venus',
    name: 'Vênus',
    type: BodyType.PLANET,
    description: 'Vênus é frequentemente chamado de planeta irmão da Terra por seu tamanho e massa semelhantes, mas suas condições são extremas. Ele é coberto por uma atmosfera muito densa de dióxido de carbono e nuvens de ácido sulfúrico, criando um efeito estufa fora de controle. Isso faz de Vênus o planeta mais quente do Sistema Solar, com temperaturas capazes de derreter chumbo. A pressão na superfície é esmagadora, equivalente a mergulhar a quase 1 km de profundidade nos oceanos da Terra.\n\nOutro destaque é sua rotação peculiar: Vênus gira no sentido contrário ao da maioria dos planetas e tão lentamente que um dia venusiano é maior do que seu ano.',
    quickFacts: [
      { label: 'Raio', value: '~6.052 km' },
      { label: 'Diâmetro', value: '~12.104 km' },
      { label: 'Massa', value: '~4,87 × 10^24 kg' },
      { label: 'Gravidade na superfície', value: '~8,87 m/s² (≈ 0,90× a da Terra)' },
      { label: 'Distância média do Sol', value: '~108,2 milhões de km (0,72 UA)' },
      { label: 'Período orbital (ano)', value: '~225 dias terrestres' },
      { label: 'Duração do dia (rotação)', value: '~243 dias terrestres (retrógrado)' },
      { label: 'Temperatura média', value: '~465–475 °C' },
      { label: 'Pressão atmosférica', value: '~92× a da Terra' }
    ],
    curiosities: [
      '🌀 Vênus gira no sentido retrógrado, de leste para oeste',
      '⏳ Um dia em Vênus é mais longo do que seu ano',
      '🌫️ Suas nuvens refletem muita luz, tornando-o o planeta mais brilhante no céu noturno',
      '🔥 É o planeta mais quente do Sistema Solar, mesmo não sendo o mais próximo do Sol',
      '🌋 Há indícios de vulcanismo recente na superfície'
    ],
    radius: 1.45,
    distance: 55,
    speed: 1.2,
    rotationSpeed: -0.000033,
    color: '#E3BB76',
    textureUrl: '/textures/texture_venus.jpg',
    axialTilt: 177.36,
    orbitalInclination: 3.39,
  },
  {
    id: 'earth',
    name: 'Terra',
    type: BodyType.PLANET,
    description: 'A Terra é um planeta rochoso de atividade intensa e dinâmica, o único conhecido a abrigar vida. Seus oceanos cobrem a maior parte da superfície e, junto com uma atmosfera rica em nitrogênio e oxigênio, mantêm um equilíbrio térmico estável e permitem a existência de água líquida em grande escala. Esse conjunto cria o ambiente ideal para ciclos essenciais à vida, como o ciclo da água e o ciclo do carbono.\n\nGeologicamente, a Terra é viva: placas tectônicas se movem, formam montanhas, abrem oceanos e reciclarm materiais do manto e da crosta. A interação entre atmosfera, oceanos e litosfera regula o clima ao longo de milhões de anos. Além disso, o campo magnético terrestre atua como um escudo contra o vento solar, ajudando a preservar a atmosfera, enquanto a Lua influencia as marés e estabiliza a inclinação do eixo, reduzindo extremos climáticos.',
    quickFacts: [
      { label: 'Raio', value: '~6.371 km' },
      { label: 'Diâmetro', value: '~12.742 km' },
      { label: 'Massa', value: '~5,97 × 10^24 kg' },
      { label: 'Gravidade na superfície', value: '~9,81 m/s²' },
      { label: 'Distância média do Sol', value: '~149,6 milhões de km (1 UA)' },
      { label: 'Período orbital (ano)', value: '~365,25 dias' },
      { label: 'Duração do dia', value: '~24 h' },
      { label: 'Temperatura média', value: '~15 °C' },
      { label: 'Atmosfera', value: 'N₂ ~78%, O₂ ~21%, outros ~1%' },
      { label: 'Cobertura de água', value: '~70% da superfície' }
    ],
    curiosities: [
      '🎵 A Terra “canta”: sismos geram vibrações que fazem o planeta oscilar em frequências baixíssimas, como um sino gigantesco',
      '🌍 Se você estivesse no espaço, veria a “linha do terminador” dividindo dia e noite — ela nunca para de se mover',
      '🧠 Há lugares onde a gravidade é ligeiramente mais fraca ou mais forte, dependendo da densidade das rochas subterrâneas',
      '🌞 A Terra está na “zona habitável” do Sol, onde a temperatura permite água líquida na superfície',
      '🧲 O campo magnético da Terra desvia partículas do vento solar, criando as auroras próximas aos polos',
      '☄️ A Terra atravessa fluxos de poeira deixados por cometas, o que provoca chuvas de meteoros anuais'
    ],
    radius: 1.5,
    distance: 81,
    speed: 1,
    rotationSpeed: 0.008,
    color: '#22A6B3',
    textureUrl: '/textures/texture_earth.jpg',
    axialTilt: 23.44,
    orbitalInclination: 0.00,
    moons: [
      {
        id: 'moon',
        name: 'Lua',
        type: BodyType.MOON,
        description: 'A Lua é o único satélite natural da Terra e o quinto maior do Sistema Solar. Ela é um corpo rochoso, sem atmosfera significativa, marcado por crateras, mares basálticos escuros e grandes planícies. Sua presença é crucial para a dinâmica do sistema Terra: a gravidade lunar influencia as marés e ajuda a estabilizar a inclinação do eixo terrestre, contribuindo para um clima mais previsível ao longo de milhões de anos.\n\nPor estar em rotação sincronizada, a Lua sempre mostra a mesma face para a Terra. Mesmo assim, ela percorre uma órbita complexa e continua a moldar nossa história científica e cultural — inclusive sendo o único corpo celeste, além da Terra, visitado por humanos.',
        quickFacts: [
          { label: 'Raio', value: '~1.737 km' },
          { label: 'Diâmetro', value: '~3.474 km' },
          { label: 'Massa', value: '~7,35 × 10^22 kg' },
          { label: 'Gravidade na superfície', value: '~1,62 m/s² (≈ 0,17× a da Terra)' },
          { label: 'Distância média da Terra', value: '~384.400 km' },
          { label: 'Período orbital', value: '~27,3 dias' },
          { label: 'Mês sinódico (fases)', value: '~29,5 dias' },
          { label: 'Temperatura', value: '~127 °C de dia e ~-173 °C à noite' },
          { label: 'Composição', value: 'Rochas silicáticas e núcleo pequeno rico em ferro' }
        ],
        curiosities: [
          '🌗 A Lua está em rotação sincronizada, por isso sempre vemos a mesma face daqui da Terra',
          '🌊 Suas forças gravitacionais, junto ao Sol, criam as marés oceânicas',
          '🌘 O “lado oculto” da Lua não é sempre escuro — ele recebe tanto Sol quanto o lado visível',
          '🛰️ Ela se afasta da Terra cerca de 3,8 cm por ano',
          '🌞 Eclipses solares só acontecem porque a Lua tem tamanho aparente semelhante ao do Sol no nosso céu',
          '🪨 Não há erosão por vento ou chuva, então crateras duram bilhões de anos'
        ],
        parentId: 'earth',
        radius: 0.27,
        distance: 5,
        speed: 1.6,
        rotationSpeed: 0.01,
        color: '#cfcfcf',
        textureUrl: '/textures/texture_moon.jpg',
      }
    ],
  },
  {
    id: 'mars',
    name: 'Marte',
    type: BodyType.PLANET,
    description: 'Marte é conhecido como o Planeta Vermelho por causa da oxidação do ferro em seu solo e poeira. É um mundo frio e desértico, com atmosfera fina de dióxido de carbono e grande variação de temperatura. Apesar disso, há fortes evidências de que no passado o planeta teve água líquida abundante, com rios, lagos e talvez até oceanos rasos.\n\nSeu relevo é extremo: abriga o Monte Olimpo, o maior vulcão do Sistema Solar, e o Valles Marineris, um cânion colossal. Marte também possui calotas polares compostas de gelo de água e gelo de dióxido de carbono, que crescem e recuam com as estações.',
    quickFacts: [
      { label: 'Raio', value: '~3.390 km' },
      { label: 'Diâmetro', value: '~6.779 km' },
      { label: 'Massa', value: '~6,42 × 10^23 kg' },
      { label: 'Gravidade na superfície', value: '~3,71 m/s² (≈ 0,38× a da Terra)' },
      { label: 'Distância média do Sol', value: '~227,9 milhões de km (1,52 UA)' },
      { label: 'Período orbital (ano)', value: '~687 dias terrestres' },
      { label: 'Duração do dia', value: '~24 h 39 min' },
      { label: 'Temperatura média', value: '~-60 °C (varia muito)' },
      { label: 'Atmosfera', value: '~95% CO₂, com argônio e nitrogênio' }
    ],
    curiosities: [
      '🌀 Marte tem as maiores tempestades de poeira do Sistema Solar, que podem cobrir o planeta inteiro',
      '🏔️ O Monte Olimpo é cerca de 3 vezes a altura do Everest',
      '🧊 Suas calotas polares crescem e encolhem a cada estação, como na Terra — mas com gelo de CO₂',
      '🌅 O pôr do sol em Marte é azul, não vermelho',
      '🌊 Há fortes evidências de água líquida no passado',
      '🔭 Marte é um dos alvos mais explorados por sondas e rovers, em busca de sinais de vida passada'
    ],
    radius: 0.8,
    distance: 102,
    speed: 0.8,
    rotationSpeed: 0.0078,
    color: '#EB4D4B',
    textureUrl: '/textures/texture_mars.jpg',
    axialTilt: 25.19,
    orbitalInclination: 1.85,
  },
  {
    id: 'jupiter',
    name: 'Júpiter',
    type: BodyType.PLANET,
    description: 'Júpiter é o maior planeta do Sistema Solar, um gigante gasoso composto principalmente de hidrogênio e hélio. Sua massa é mais que o dobro da soma de todos os outros planetas, e sua gravidade influencia fortemente a dinâmica do sistema, capturando e desviando cometas e asteroides. A atmosfera de Júpiter é turbulenta, marcada por faixas coloridas e gigantescas tempestades, sendo a mais famosa a Grande Mancha Vermelha, ativa há séculos.\n\nApesar de não ter uma superfície sólida definida, Júpiter possui um núcleo denso e um poderoso campo magnético — o mais intenso entre os planetas — que cria auroras espetaculares. Ele também abriga um vasto sistema de luas, incluindo os quatro satélites galileanos: Io, Europa, Ganimedes e Calisto.',
    quickFacts: [
      { label: 'Raio', value: '~69.911 km' },
      { label: 'Diâmetro', value: '~139.820 km' },
      { label: 'Massa', value: '~1,898 × 10^27 kg' },
      { label: 'Gravidade na superfície', value: '~24,79 m/s² (≈ 2,53× a da Terra)' },
      { label: 'Distância média do Sol', value: '~778,5 milhões de km (5,2 UA)' },
      { label: 'Período orbital (ano)', value: '~11,86 anos terrestres' },
      { label: 'Duração do dia', value: '~9 h 56 min' },
      { label: 'Temperatura média (topo das nuvens)', value: '~-110 °C' },
      { label: 'Composição', value: 'Hidrogênio e hélio, com traços de metano, amônia e água' }
    ],
    curiosities: [
      '🛡️ Júpiter funciona como um “escudo gravitacional”: sua enorme gravidade desvia ou captura muitos asteroides e cometas que poderiam atingir a Terra.',
      '🌀 A Grande Mancha Vermelha é uma tempestade maior que a Terra, ativa há pelo menos 350 anos',
      '⚡ Júpiter emite mais energia do que recebe do Sol, devido ao calor interno remanescente',
      '🧲 Seu campo magnético é tão forte que poderia destruir aparelhos eletrônicos sem proteção adequada',
      '🌙 Ele tem dezenas de luas — e quatro delas são mundos complexos por si só',
      '🪐 Um sistema de anéis tênues circunda Júpiter, embora pouco visível',
      '💨 Ventos na atmosfera de Júpiter podem atingir velocidades de até 600 km/h',
      '🌩️ Júpiter é conhecido por suas intensas tempestades elétricas, que produzem relâmpagos muito mais poderosos que os da Terra'
    ],
    radius: 6.5,
    distance: 165,
    speed: 0.4,
    rotationSpeed: 0.0195,
    color: '#F9CA24',
    textureUrl: '/textures/texture_jupiter.jpg',
    axialTilt: 3.13,
    orbitalInclination: 1.31,
    moons: [
      {
        id: 'io',
        name: 'Io',
        type: BodyType.MOON,
        description: 'Io é a lua mais vulcanicamente ativa do Sistema Solar. Sua superfície é constantemente renovada por centenas de vulcões e vastos fluxos de lava, tingidos por compostos de enxofre que criam um mosaico de cores. Essa atividade extrema é causada pelas intensas forças de maré gravitacional de Júpiter, que aquecem o interior de Io e geram um verdadeiro “inferno geológico”.',
        quickFacts: [
          { label: 'Raio', value: '~1.821 km' },
          { label: 'Diâmetro', value: '~3.643 km' },
          { label: 'Massa', value: '~8,93 × 10^22 kg' },
          { label: 'Gravidade na superfície', value: '~1,80 m/s² (≈ 0,18× a da Terra)' },
          { label: 'Distância de Júpiter', value: '~421.700 km' },
          { label: 'Período orbital', value: '~1,77 dias' },
          { label: 'Atmosfera', value: 'Muito tênue, rica em dióxido de enxofre (SO₂)' },
          { label: 'Temperatura média', value: '~-130 °C (com regiões vulcânicas muito mais quentes)' }
        ],
        curiosities: [
          '🌋 Io tem as erupções vulcânicas mais energéticas conhecidas',
          '🟡 Sua superfície muda rapidamente, com lava fresca cobrindo antigas crateras',
          '🔥 A força de maré de Júpiter “amassa” Io, gerando calor interno intenso',
          '🌫️ Sua fina atmosfera colapsa e se refaz conforme a lua entra e sai da sombra de Júpiter',
          '🛰️ As plumas vulcânicas podem ultrapassar 500 km de altura'
        ],
        parentId: 'jupiter',
        radius: 0.25,
        distance: 8.5,
        speed: 2.2,
        rotationSpeed: 0.02,
        color: '#d8a15d',
        textureUrl: '/textures/texture_io.jpg'
      },
      {
        id: 'europa',
        name: 'Europa',
        type: BodyType.MOON,
        description: 'Europa é uma lua gelada com superfície incrivelmente lisa, cruzada por longas fraturas e linhas avermelhadas. Abaixo de sua crosta de gelo existe um oceano global de água líquida, possivelmente com mais água do que todos os oceanos da Terra juntos. A energia das marés gravitacionais de Júpiter pode manter esse oceano aquecido, tornando Europa um dos locais mais promissores para buscar vida fora da Terra.',
        quickFacts: [
          { label: 'Raio', value: '~1.561 km' },
          { label: 'Diâmetro', value: '~3.122 km' },
          { label: 'Massa', value: '~4,80 × 10^22 kg' },
          { label: 'Gravidade na superfície', value: '~1,31 m/s² (≈ 0,13× a da Terra)' },
          { label: 'Distância de Júpiter', value: '~671.100 km' },
          { label: 'Período orbital', value: '~3,55 dias' },
          { label: 'Crosta de gelo', value: 'Varia entre dezenas de km de espessura' },
          { label: 'Temperatura média', value: '~-160 °C' }
        ],
        curiosities: [
          '🧊 A superfície é tão jovem que tem poucas crateras de impacto',
          '🌊 O oceano subterrâneo pode estar em contato com um fundo rochoso, criando fontes hidrotermais',
          '🧲 Europa tem interações magnéticas que sugerem um oceano salgado',
          '🔎 Missões futuras focam em perfurar o gelo e buscar sinais de vida',
          '✨ Suas fraturas podem liberar material do oceano para o espaço'
        ],
        parentId: 'jupiter',
        radius: 0.22,
        distance: 10,
        speed: 1.8,
        rotationSpeed: 0.018,
        color: '#cfcfcf',
        textureUrl: '/textures/texture_europa.jpg'
      },
      {
        id: 'ganymede',
        name: 'Ganimedes',
        type: BodyType.MOON,
        description: 'Ganimedes é a maior lua do Sistema Solar — maior até que o planeta Mercúrio — e possui uma composição de gelo de água e rochas. Sua superfície mostra um contraste de terrenos antigos, escuros e craterados, com regiões mais claras e sulcadas que indicam atividade geológica passada. Ganimedes é a única lua conhecida com campo magnético próprio, gerando uma magnetosfera que interage com a de Júpiter.\n\nEvidências sugerem a presença de um oceano subterrâneo salgado, possivelmente em camadas entre o gelo e o manto rochoso, tornando Ganimedes um alvo importante na busca por ambientes habitáveis.',
        quickFacts: [
          { label: 'Raio', value: '~2.634 km' },
          { label: 'Diâmetro', value: '~5.268 km' },
          { label: 'Massa', value: '~1,48 × 10^23 kg' },
          { label: 'Gravidade na superfície', value: '~1,43 m/s² (≈ 0,15× a da Terra)' },
          { label: 'Distância de Júpiter', value: '~1.070.400 km' },
          { label: 'Período orbital', value: '~7,15 dias' },
          { label: 'Temperatura média', value: '~-160 °C' },
          { label: 'Composição', value: 'Gelo de água e rochas silicáticas' }
        ],
        curiosities: [
          '🧲 É a única lua com campo magnético próprio conhecido',
          '🌊 Indícios apontam para um oceano subterrâneo salgado em múltiplas camadas',
          '🔁 Faz parte da ressonância orbital 1:2:4 com Io e Europa',
          '🪐 Se orbitasse o Sol, seria classificada como planeta',
          '🔭 Foi uma das quatro luas descobertas por Galileu em 1610'
        ],
        parentId: 'jupiter',
        radius: 0.35,
        distance: 12,
        speed: 1.4,
        rotationSpeed: 0.015,
        color: '#b8b2a1',
        textureUrl: '/textures/texture_ganimedes.jpg'
      },
      {
        id: 'callisto',
        name: 'Calisto',
        type: BodyType.MOON,
        description: 'Calisto é a lua mais craterada do Sistema Solar, com uma superfície extremamente antiga e praticamente inalterada há bilhões de anos. Ela possui poucas evidências de atividade geológica, o que a torna um registro preservado da história de impactos no sistema joviano.',
        quickFacts: [
          { label: 'Raio', value: '~2.410 km' },
          { label: 'Diâmetro', value: '~4.821 km' },
          { label: 'Massa', value: '~1,08 × 10^23 kg' },
          { label: 'Gravidade na superfície', value: '~1,24 m/s² (≈ 0,13× a da Terra)' },
          { label: 'Distância de Júpiter', value: '~1.882.700 km' },
          { label: 'Período orbital', value: '~16,7 dias' },
          { label: 'Temperatura média', value: '~-140 °C' },
          { label: 'Composição', value: 'Mistura de gelo de água e rochas' }
        ],
        curiosities: [
          '🕳️ A bacia de Valhalla é uma das maiores estruturas de impacto conhecidas',
          '🧊 Pode ter um oceano subterrâneo, apesar de ser geologicamente inativa',
          '🛰️ É considerada um local relativamente estável para futuras bases humanas no sistema joviano',
          '⏳ Sua superfície preserva marcas de impactos desde os primórdios do Sistema Solar',
          '🌌 É a lua galileana mais distante de Júpiter'
        ],
        parentId: 'jupiter',
        radius: 0.32,
        distance: 14,
        speed: 1.1,
        rotationSpeed: 0.012,
        color: '#a88f6f',
        textureUrl: '/textures/texture_calisto.jpg'
      }
    ],
  },
  {
    id: 'saturn',
    name: 'Saturno',
    type: BodyType.PLANET,
    description: 'Saturno é o segundo maior planeta do Sistema Solar e é famoso por seu impressionante sistema de anéis. Esses anéis são compostos principalmente por gelo, poeira e fragmentos rochosos, organizados em inúmeras estruturas finas. Saturno é um gigante gasoso de baixa densidade, formado principalmente por hidrogênio e hélio, com uma atmosfera dinâmica e ventos intensos.\n\nSeu interior é dominado por hidrogênio e hélio sob altíssima pressão, formando camadas de hidrogênio líquido e metálico. Essa estrutura interna gera um campo magnético expressivo e libera calor remanescente, fazendo Saturno irradiar mais energia do que recebe do Sol. Em sua atmosfera, grandes sistemas de tempestades podem durar meses, e há um padrão hexagonal persistente no polo norte que intriga os cientistas.',
    quickFacts: [
      { label: 'Raio', value: '~58.232 km' },
      { label: 'Diâmetro', value: '~116.464 km' },
      { label: 'Massa', value: '~5,68 × 10^26 kg' },
      { label: 'Gravidade na superfície', value: '~10,44 m/s² (≈ 1,07× a da Terra)' },
      { label: 'Distância média do Sol', value: '~1,43 bilhões de km (9,58 UA)' },
      { label: 'Período orbital (ano)', value: '~29,45 anos terrestres' },
      { label: 'Duração do dia', value: '~10 h 33 min' },
      { label: 'Temperatura média (topo das nuvens)', value: '~-140 °C' },
      { label: 'Composição', value: 'Hidrogênio e hélio, com traços de metano e amônia' }
    ],
    curiosities: [
      '💍 Seus anéis têm apenas dezenas a centenas de metros de espessura, mas se estendem por centenas de milhares de quilômetros',
      '🪐 Seus anéis influenciam a dinâmica do planeta, afetando campo magnético e partículas carregadas',
      '🌀 Saturno tem um “hexágono” persistente de nuvens no polo norte, uma estrutura atmosférica única',
      '🌬️ Ventos em Saturno podem atingir velocidades de até 1.800 km/h, muito mais rápidos que os furacões terrestres',
      '🧭 O campo magnético é quase perfeitamente alinhado com o eixo de rotação — algo anormal entre planetas'
    ],
    radius: 5.5,
    distance: 225,
    speed: 0.3,
    rotationSpeed: 0.0178,
    color: '#F0932B',
    hasRings: true,
    ringColor: '#dcdcdc',
    ringTextureUrl: '/textures/texture_saturn_rings.png',
    textureUrl: '/textures/texture_saturn.jpg',
    axialTilt: 26.73,
    orbitalInclination: 2.49,
    moons: [
      {
        id: 'titan',
        name: 'Titã',
        type: BodyType.MOON,
        description: 'Titã é a maior lua de Saturno e a segunda maior do Sistema Solar. Ela possui uma atmosfera densa, rica em nitrogênio, com uma névoa alaranjada que oculta grande parte da superfície. Titã é único por ter líquidos estáveis em sua superfície: rios, lagos e mares de metano e etano, além de “chuvas” desses hidrocarbonetos.\n\nSob a crosta gelada, pode existir um oceano subterrâneo de água líquida misturada com amônia. Sua química complexa e atmosfera espessa fazem de Titã um dos mundos mais intrigantes do Sistema Solar.',
        quickFacts: [
          { label: 'Raio', value: '~2.575 km' },
          { label: 'Diâmetro', value: '~5.150 km' },
          { label: 'Massa', value: '~1,35 × 10^23 kg' },
          { label: 'Gravidade na superfície', value: '~1,35 m/s² (≈ 0,14× a da Terra)' },
          { label: 'Distância de Saturno', value: '~1.221.870 km' },
          { label: 'Período orbital', value: '~15,95 dias' },
          { label: 'Temperatura média', value: '~-179 °C' },
          { label: 'Atmosfera', value: 'Nitrogênio dominante com metano e traços orgânicos' }
        ],
        curiosities: [
          '🌫️ A atmosfera de Titã é mais densa que a da Terra',
          '🧲 Titã não tem campo magnético próprio, ficando exposto ao ambiente magnético de Saturno',
          '🌧️ Chove metano e etano, formando ciclos climáticos completos (nuvens, chuva, rios e lagos)',
          '🛶 Seus mares de hidrocarbonetos líquidos já foram mapeados por sonda',
          '🧪 A química atmosférica forma moléculas orgânicas complexas, chamadas de tolina',
          '🪽 Com asas artificiais, um humano poderia voar batendo os braços devido à baixa gravidade e alta densidade do ar',
        ],
        parentId: 'saturn',
        radius: 0.34,
        distance: 16,
        speed: 1.2,
        rotationSpeed: 0.012,
        color: '#c9a46b',
        textureUrl: '/textures/texture_titan.jpg'
      },
      {
        id: 'enceladus',
        name: 'Encélado',
        type: BodyType.MOON,
        description: 'Encélado é uma lua pequena e brilhante de Saturno, coberta por gelo extremamente refletivo. Ela é famosa por seus gêiseres no polo sul, que lançam jatos de vapor de água, gelo e compostos orgânicos para o espaço, formando o anel E de Saturno. Esses jatos indicam a presença de um oceano global subterrâneo de água líquida sob a crosta gelada.\n\nAs interações gravitacionais com Saturno aquecem o interior da lua, permitindo atividade geológica e tornando Encélado um dos lugares mais promissores na busca por vida fora da Terra.',
        quickFacts: [
          { label: 'Raio', value: '~252 km' },
          { label: 'Diâmetro', value: '~504 km' },
          { label: 'Massa', value: '~1,08 × 10^20 kg' },
          { label: 'Gravidade na superfície', value: '~0,113 m/s² (≈ 0,01× a da Terra)' },
          { label: 'Distância de Saturno', value: '~238.000 km' },
          { label: 'Período orbital', value: '~1,37 dias' },
          { label: 'Temperatura média', value: '~-200 °C' },
          { label: 'Composição', value: 'Gelo de água e núcleo rochoso' }
        ],
        curiosities: [
          '💧 Os jatos de água de Encélado contêm sais e moléculas orgânicas complexas',
          '🧊 É um dos objetos mais brilhantes do Sistema Solar por seu gelo limpo',
          '🌌 Seus gêiseres alimentam diretamente o anel E de Saturno',
          '🔥 O aquecimento por marés mantém o oceano subterrâneo líquido',
          '🔬 É um alvo prioritário para missões que buscam sinais de vida'
        ],
        parentId: 'saturn',
        radius: 0.08,
        distance: 13,
        speed: 2.4,
        rotationSpeed: 0.02,
        color: '#e6e6e6',
        textureUrl: '/textures/texture_encelado.jpg'
      }
    ],
  },
  {
    id: 'uranus',
    name: 'Urano',
    type: BodyType.PLANET,
    description: 'Urano é um gigante de gelo com coloração azul-esverdeada causada pela presença de metano em sua atmosfera. Diferente dos gigantes gasosos, sua composição inclui uma grande fração de água, amônia e metano em forma de “gelo” sob altas pressões. O planeta é famoso por sua inclinação extrema: seu eixo está inclinado quase 98°, fazendo com que Urano “role” ao redor do Sol.\n\nEssa orientação gera estações extremamente longas e incomuns, com cada polo recebendo luz solar contínua por décadas. Urano também possui um sistema de anéis tênues e dezenas de luas, além de um campo magnético bastante inclinado e deslocado em relação ao centro do planeta.',
    quickFacts: [
      { label: 'Raio', value: '~25.362 km' },
      { label: 'Diâmetro', value: '~50.724 km' },
      { label: 'Massa', value: '~8,68 × 10^25 kg' },
      { label: 'Gravidade na superfície', value: '~8,69 m/s² (≈ 0,89× a da Terra)' },
      { label: 'Distância média do Sol', value: '~2,87 bilhões de km (19,2 UA)' },
      { label: 'Período orbital (ano)', value: '~84 anos terrestres' },
      { label: 'Duração do dia', value: '~17 h 14 min (retrógrado)' },
      { label: 'Temperatura média', value: '~-224 °C (uma das mais frias)' },
      { label: 'Composição', value: 'Gelo de água, amônia e metano + H/He' }
    ],
    curiosities: [
      '🧭 O campo magnético de Urano é inclinado e deslocado, diferente de quase todos os outros planetas',
      '🌗 Cada estação em Urano dura cerca de 21 anos terrestres',
      '💍 Seus anéis são escuros e muito estreitos, difíceis de observar',
      '🔭 Foi o primeiro planeta descoberto com telescópio, em 1781',
      '🧊 É o planeta mais frio do Sistema Solar, apesar de não ser o mais distante'
    ],
    radius: 2.6,
    distance: 285,
    speed: 0.2,
    rotationSpeed: -0.0111,
    color: '#7ED6DF',
    hasRings: true,
    ringColor: '#9ab0c7',
    ringTextureUrl: '/textures/texture_uranus_ring.png',
    ringInnerRadiusMultiplier: 1.15,
    ringOuterRadiusMultiplier: 1.55,
    textureUrl: '/textures/texture_uranus.jpg',
    axialTilt: 97.77,
    orbitalInclination: 0.77,
  },
  {
    id: 'neptune',
    name: 'Netuno',
    type: BodyType.PLANET,
    description: 'Netuno é o planeta mais distante do Sol e um gigante de gelo, com atmosfera rica em hidrogênio, hélio e metano — o que lhe dá a coloração azul intensa. Apesar de sua distância e baixas temperaturas, Netuno é extremamente dinâmico: ventos supersônicos e tempestades gigantescas marcam sua atmosfera, incluindo a famosa Grande Mancha Escura observada pela sonda Voyager 2.\n\nSeu interior é composto por uma mistura de água, amônia e metano sob altíssima pressão, acima de um núcleo rochoso. Netuno também possui um sistema de anéis tênues e um conjunto de luas, com Tritão se destacando por sua órbita retrógrada e atividade criovulcânica.',
    quickFacts: [
      { label: 'Raio', value: '~24.622 km' },
      { label: 'Diâmetro', value: '~49.244 km' },
      { label: 'Massa', value: '~1,02 × 10^26 kg' },
      { label: 'Gravidade na superfície', value: '~11,15 m/s² (≈ 1,14× a da Terra)' },
      { label: 'Distância média do Sol', value: '~4,50 bilhões de km (30,1 UA)' },
      { label: 'Período orbital (ano)', value: '~165 anos terrestres' },
      { label: 'Duração do dia', value: '~16 h 6 min' },
      { label: 'Temperatura média', value: '~-214 °C' },
      { label: 'Composição', value: 'H/He com metano; interior rico em “gelo” (água, amônia, metano)' }
    ],
    curiosities: [
      '💨 Netuno tem os ventos mais rápidos do Sistema Solar, podendo ultrapassar 2.000 km/h',
      '🔵 Sua cor azul é intensificada por absorção de luz vermelha pelo metano',
      '🌀 A Grande Mancha Escura foi um grande sistema de tempestades, semelhante à Mancha de Júpiter',
      '🧭 Seu campo magnético é inclinado e deslocado do centro, como o de Urano',
      '🔭 Foi o primeiro planeta descoberto por previsão matemática antes de ser observado'
    ],
    radius: 2.5,
    distance: 345,
    speed: 0.1,
    rotationSpeed: 0.0119,
    color: '#4834D4',
    textureUrl: '/textures/texture_neptune.jpg',
    axialTilt: 28.32,
    orbitalInclination: 1.77,
    moons: [
      {
        id: 'triton',
        name: 'Tritão',
        type: BodyType.MOON,
        description: 'Tritão é a maior lua de Netuno e um dos mundos mais intrigantes do Sistema Solar. Ele orbita em sentido retrógrado, o que sugere que foi capturado da região do Cinturão de Kuiper, sendo semelhante a Plutão. Sua superfície é coberta por gelo de nitrogênio, com terrenos variados e sinais de atividade criovulcânica.\n\nApesar das temperaturas extremamente baixas, Tritão apresenta gêiseres que lançam material congelado para a atmosfera, mostrando que seu interior ainda retém algum calor. No futuro, sua órbita pode decair e levar a uma possível fragmentação ao se aproximar demais de Netuno.',
        quickFacts: [
          { label: 'Raio', value: '~1.353 km' },
          { label: 'Diâmetro', value: '~2.706 km' },
          { label: 'Massa', value: '~2,14 × 10^22 kg' },
          { label: 'Gravidade na superfície', value: '~0,78 m/s² (≈ 0,08× a da Terra)' },
          { label: 'Distância de Netuno', value: '~354.800 km' },
          { label: 'Período orbital', value: '~5,88 dias (retrógrado)' },
          { label: 'Temperatura média', value: '~-235 °C' },
          { label: 'Composição', value: 'Gelo de nitrogênio, metano e água; núcleo rochoso' }
        ],
        curiosities: [
          '🔄 Tritão é o único grande satélite do Sistema Solar em órbita retrógrada',
          '❄️ É um dos objetos mais frios conhecidos, com atmosfera muito tênue de nitrogênio',
          '🌋 Seus gêiseres criovulcânicos foram vistos pela Voyager 2',
          '🪐 É provavelmente um objeto capturado do Cinturão de Kuiper',
          '🧭 Sua órbita está lentamente diminuindo, podendo levar a colisão ou fragmentação no futuro distante'
        ],
        parentId: 'neptune',
        radius: 0.2,
        distance: 6,
        speed: 1.6,
        rotationSpeed: 0.015,
        color: '#cfcfd6',
        textureUrl: '/textures/texture_triton.jpg'
      }
    ],
  }
];
